services:
  node:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./:/app
    depends_on:
      - mysql
  mysql:
    image: mysql:8.1.0
    ports:
      - 3307:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=tanphandev
      - MYSQL_ROOT_PASSWORD=123456
volumes:
  db-data: {}
